### PR TITLE
get rid of all legacy code and create meta gem pulling in useful gems

### PR DESCRIPTION
**Pull request by minad**
* sciruby (Empty gem, only version information)
* sciruby-full (Pulls in many other useful gems)

### CODE REVIEW

**Comment by minad** [comment]
thx! I expected more discussion ;)

Please take a look at the Gemfile which holds the list of scientific gems recommened by "sciruby" and installed by "sciruby-full". Maybe you want to add/remove some?

We could also do another release very soon - there is not much to test here. This would be useful for the Dockerfile in sciruby-notebooks which could just install sciruby-full then.

https://github.com/SciRuby/sciruby-notebooks/blob/master/Dockerfile#L22

Could you add me to the sciruby gem on rubygems.org? Then I would do it if you agree.

**Comment by minad** [comment]
We could also create a gem `sciruby-light` which pulls in _some_ gems, but I would refrain from it since this is just too much of a discussion and a matter of opinion what is needed and what is not (also depending on what you want to do biology, statistics, ...).

**Comment by mohawkjohn** [comment]
I think you have to add yourself to the authors list in the gemspec for me to add you on Rubygems.org. I'm not sure how else to set permissions there (or even if that works).

**Comment by mohawkjohn** [comment]
@minad I did just give you admin access to this gem, FYI.

**Comment by minad** [comment]
thx! `gem owner sciruby -a mail@daniel-mendler.de`

**Comment by mohawkjohn** [comment]
Done.

**Comment by minad** [comment]
thx :smiley:

**Pull request merged**
